const http = require('http');
const fetch = require('node-fetch');
const urls = [ 

  
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ALINEA BEAUMONT&adressechantier=ZA BORDEVIEILLE&codepostalcommercial=82500&villecommercial=BEAUMONT DE LOMAGNE&telephonecommercial=06 72 83 41 21&surface=1400&tarifaumetrecarre=0.75&caht=1050&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ALINEA LAUTREC&adressechantier=LIEU DIT LA PLAINE&codepostalcommercial=81440&villecommercial=LAUTREC&telephonecommercial=05 63 70 81 81&surface=1320&tarifaumetrecarre=0.75&caht=990&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ALINEA LECTOURE&adressechantier=ZA DE LECTOURE&codepostalcommercial=32700&villecommercial=LECTOURE&telephonecommercial=&surface=3970&tarifaumetrecarre=0.75&caht=2977.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ANGELAUD&adressechantier=BERNADERE&codepostalcommercial=47600&villecommercial=ESPIENS&telephonecommercial=06 79 02 78 31&surface=725&tarifaumetrecarre=0.75&caht=543.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ARCALY GREEN&adressechantier=Allée de Bruxelles&codepostalcommercial=83870&villecommercial=SIGNES&telephonecommercial=06 09 52 05 39&surface=3240&tarifaumetrecarre=0.75&caht=2430&datedederniernettoyage=20/7/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ATM&adressechantier=ZA DU CONFLUENT ROUTE DE MAHOURAT&codepostalcommercial=47160&villecommercial=DAMAZAN&telephonecommercial=05 53 88 00 23&surface=1358&tarifaumetrecarre=0.75&caht=1018.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=AUBELEAU&adressechantier=LIEU DIT BLAYAC&codepostalcommercial=12490&villecommercial=ST ROME DE CERNON&telephonecommercial=06 20 97 07 93&surface=1190&tarifaumetrecarre=0.75&caht=892.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BABU&adressechantier=LIEU DIT BOSNEGRE&codepostalcommercial=47410&villecommercial=ST COLOMBE DE LAUZUN&telephonecommercial=06 70 02 92 24&surface=296&tarifaumetrecarre=0.75&caht=222&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BARDOU FI&adressechantier=LIEU DIT COMBELASSE&codepostalcommercial=81440&villecommercial=LAUTREC&telephonecommercial=&surface=600&tarifaumetrecarre=0.75&caht=450&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BAUDON&adressechantier=LIEU DIT GRAND BOURDIEU&codepostalcommercial=47600&villecommercial=ESPIENS&telephonecommercial=06 12 48 59 58&surface=714&tarifaumetrecarre=0.75&caht=535.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BIOCOOP&adressechantier=PONCHUT&codepostalcommercial=47130&villecommercial=PORT STE MARIE&telephonecommercial=&surface=1018&tarifaumetrecarre=0.75&caht=763.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BOALIA&adressechantier=RUE GAY LUSSAC&codepostalcommercial=47400&villecommercial=TONNEINS&telephonecommercial=&surface=21000&tarifaumetrecarre=0.75&caht=15,750&datedederniernettoyage=28/3/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BORREDON&adressechantier=LIEU DIT LA VIARNESE&codepostalcommercial=82150&villecommercial=MONTAIGU DE QUERCY&telephonecommercial=06 67 77 73 18&surface=725&tarifaumetrecarre=0.75&caht=543.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BOULODROME DE GRASSE&adressechantier=QUARTIER SAINT ANTOINE&codepostalcommercial=06130&villecommercial=GRASSE&telephonecommercial=06 12 29 62 83&surface=533&tarifaumetrecarre=0.75&caht=399.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=BOURGOIN - AGEN CENTRE&adressechantier=6738 RUE G. CLEMENCEAU&codepostalcommercial=47420&villecommercial=BON ENCONTRE&telephonecommercial=06 83 44 75 19&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CANTINE DE JONQUIERES&adressechantier=AVENUE PIERRE DE COUBERTIN&codepostalcommercial=84150&villecommercial=JONQUIERES&telephonecommercial=06 11 71 44 28&surface=224&tarifaumetrecarre=0.75&caht=168&datedederniernettoyage=&emailcommercial=technique@jonquieres.fr',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CARIMALO 1&adressechantier=TREYLAGUES&codepostalcommercial=47140&villecommercial=ST SYLVESTRE SUR LOT&telephonecommercial=06 82 66 40 12&surface=1321&tarifaumetrecarre=0.75&caht=990.75&datedederniernettoyage=14/3/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CARIMALO 2&adressechantier=LIEU DIT LONGAGNE&codepostalcommercial=47140&villecommercial=ST SYLVESTRE SUR LOT&telephonecommercial=06 82 66 40 12&surface=1321&tarifaumetrecarre=0.75&caht=990.75&datedederniernettoyage=14/3/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CASSE&adressechantier=LIEU DIT SOUBES&codepostalcommercial=47250&villecommercial=ROMESTAING&telephonecommercial=06 74 64 81 49&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CCV&adressechantier=RUE PAUL LANGEVIN&codepostalcommercial=47300&villecommercial=VILLENEUVE SUR LOT&telephonecommercial=06 08 09 87 03&surface=1364&tarifaumetrecarre=0.75&caht=1023&datedederniernettoyage=25/5/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CENTRE DE TRI DE CREON&adressechantier=LE PASTIN&codepostalcommercial=33670&villecommercial=LA SAUVE&telephonecommercial=&surface=523&tarifaumetrecarre=0.75&caht=392.25&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CENTRE DE TRI MIRAMONT&adressechantier=RUE VILLANOVA&codepostalcommercial=47800&villecommercial=MIRAMONT DE GUYENNE&telephonecommercial=&surface=664&tarifaumetrecarre=0.75&caht=498&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CESAREO&adressechantier=LIEU DIT CASTEX&codepostalcommercial=47310&villecommercial=ESTILLAC&telephonecommercial=05 53 96 31 95&surface=680&tarifaumetrecarre=0.75&caht=510&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=CHLOERIA&adressechantier=LIEU DIT DEVANT LANNE&codepostalcommercial=65380&villecommercial=LANNE&telephonecommercial=05 62 45 41 69 / 06 87 55 75 37&surface=1186&tarifaumetrecarre=0.75&caht=889.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=COLLEGE ALARIC&adressechantier=RUE DU COLLEGE&codepostalcommercial=11700&villecommercial=CAPENDU&telephonecommercial=&surface=254&tarifaumetrecarre=0.75&caht=190.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=COLLEGE BRASSENS&adressechantier=1 RUE DE L\'ALZEAU&codepostalcommercial=11000&villecommercial=NARBONNE&telephonecommercial=&surface=248&tarifaumetrecarre=0.75&caht=186&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=COLLEGE GASTON BONHEUR&adressechantier=50 BOULERVARD DU MINERVOIS&codepostalcommercial=11800&villecommercial=TREBES&telephonecommercial=&surface=640&tarifaumetrecarre=0.75&caht=480&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=COLLEGE LA NADIERE&adressechantier=405 BOULEVARD VALS&codepostalcommercial=11210&villecommercial=PORT LA NOUVELLE&telephonecommercial=04 68 48 03 56&surface=257&tarifaumetrecarre=0.75&caht=192.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=COLLEGE MONTESQUIEU&adressechantier=9006 AVENUE MONTESQUIEU&codepostalcommercial=11100&villecommercial=NARBONNE&telephonecommercial=&surface=630&tarifaumetrecarre=0.75&caht=472.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=COLOMB&adressechantier=CHEMIN DES AUREOLES&codepostalcommercial=84150&villecommercial=JONQUIERES&telephonecommercial=&surface=1403&tarifaumetrecarre=0.75&caht=1052.25&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=DISTRIPUB&adressechantier=190 AVENUE DE LA COTE D\'ARGENT&codepostalcommercial=33380&villecommercial=BIGANOS&telephonecommercial=&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=DUPESSEY RUMILLY&adressechantier=ROUTE D\'AIX LES BAINS&codepostalcommercial=74150&villecommercial=RUMILLY&telephonecommercial=06 43 86 45 62&surface=1865&tarifaumetrecarre=0.75&caht=1398.75&datedederniernettoyage=8/9/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ECOLE TEMPLE SUR LOT&adressechantier=LIEU DIT PEGALOUS&codepostalcommercial=47110&villecommercial=LE TEMPLE SUR LOT&telephonecommercial=&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ECURIE DE PATCHANKA&adressechantier=QUARTIER COURREAU CHEMIN DE LA PAILLASSE&codepostalcommercial=30130&villecommercial=PONT ST ESPRIT&telephonecommercial=06 86 16 33 08&surface=1782&tarifaumetrecarre=0.75&caht=1336.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ECURIES FERRINI&adressechantier=ROUTE DE VENDARGUES&codepostalcommercial=34820&villecommercial=TEYRAN&telephonecommercial=06 63 91 51 76&surface=693&tarifaumetrecarre=0.75&caht=519.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=EXTENSION USINE&adressechantier=ZAC DES CHAMPS DE LESCAZE&codepostalcommercial=47310&villecommercial=ROQUEFORT&telephonecommercial=&surface=14988&tarifaumetrecarre=0.75&caht=11,241&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=FABRE 1 et 2&adressechantier=CAPPELAT&codepostalcommercial=47290&villecommercial=SAINT PASTOUR&telephonecommercial=&surface=1252&tarifaumetrecarre=0.75&caht=939&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=FEBUS GAILLAC&adressechantier=BEZES&codepostalcommercial=81600&villecommercial=GAILLAC&telephonecommercial=&surface=7460&tarifaumetrecarre=0.75&caht=5595&datedederniernettoyage=25/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=GAEC DE LA FONTAINE&adressechantier=LIEU DIT LE GARROS&codepostalcommercial=32480&villecommercial=LIGARDES&telephonecommercial=06 16 41 26 75&surface=725&tarifaumetrecarre=0.75&caht=543.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=GAEC GALZIN&adressechantier=MAS DE SESTIER&codepostalcommercial=12360&villecommercial=GISSAC&telephonecommercial=06 75 04 38 10&surface=726&tarifaumetrecarre=0.75&caht=544.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=GAURRAT&adressechantier=CHEMIN DE MORLANNE&codepostalcommercial=61600&villecommercial=BUROS&telephonecommercial=05 59 84 68 34&surface=594&tarifaumetrecarre=0.75&caht=445.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=GELADE&adressechantier=ZAC DE LA BORIE RUE DES ENTREPENEURS&codepostalcommercial=47480&villecommercial=PONT DU CASSE&telephonecommercial=06 08 23 52 78&surface=298&tarifaumetrecarre=0.75&caht=223.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=GELADE REGIS&adressechantier=ROUTE DE CARCASSONNE DE119 LIEU DIT LARCHE&codepostalcommercial=09500&villecommercial=MIREPOIX&telephonecommercial=04 30 07 34 06&surface=1370&tarifaumetrecarre=0.75&caht=1027.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=GUASCONI&adressechantier=LARTIGAU&codepostalcommercial=47310&villecommercial=ST VINCENT DE LAMONTJOIE&telephonecommercial=06 16 33 52 15&surface=873&tarifaumetrecarre=0.75&caht=654.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=HABITAT SOLAIRE&adressechantier=ZAC DES CHAMPS DE LESCAZE&codepostalcommercial=47310&villecommercial=ROQUEFORT&telephonecommercial=&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=JOANNIC&adressechantier=saint loubert&codepostalcommercial=33690&villecommercial=GRIGNOLS&telephonecommercial=06 86 92 34 00&surface=1320&tarifaumetrecarre=0.75&caht=990&datedederniernettoyage=27/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=JOQUEVIEL&adressechantier=LIEU DIT MASCARENS&codepostalcommercial=81440&villecommercial=LAUTREC&telephonecommercial=06 78 34 83 31&surface=594&tarifaumetrecarre=0.75&caht=445.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=KDI BLANQUEFORT&adressechantier=1 RUE GEORGES GUYNEMER&codepostalcommercial=33290&villecommercial=BLANQUEFORT&telephonecommercial=05 56 29 27 51&surface=5041&tarifaumetrecarre=0.75&caht=3780.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=KDI COLOMIERS&adressechantier=ZI EN JACCA CHEMIN DE LA NASQUE&codepostalcommercial=31770&villecommercial=COLOMIERS&telephonecommercial=05 61 36 06 60&surface=6334&tarifaumetrecarre=0.75&caht=4750.50&datedederniernettoyage=29/8/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LARROCHE&adressechantier=LIEU DIT PADIERES&codepostalcommercial=47600&villecommercial=ESPIENS&telephonecommercial=06 82 19 92 56&surface=714&tarifaumetrecarre=0.75&caht=535.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LES GLAUDETS&adressechantier=BOIS BEDAT&codepostalcommercial=33190&villecommercial=HURE&telephonecommercial=06 31 84 15 86&surface=1687&tarifaumetrecarre=0.75&caht=1265.25&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LES VERGERS D\'ESCOUTE&adressechantier=LIEU DIT ROUGE&codepostalcommercial=47110&villecommercial=STE LIVRADE SUR LOT&telephonecommercial=05 53 41 25 42&surface=7500&tarifaumetrecarre=0.75&caht=5625&datedederniernettoyage=3/1/2022&emailcommercial=sylvain@escoute.fr',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LOCAMOISSON&adressechantier=LIEU DIT AU GRICHOU&codepostalcommercial=32300&villecommercial=BERDOUES&telephonecommercial=  05 62 66 51 44&surface=5316&tarifaumetrecarre=0.75&caht=3987&datedederniernettoyage=20/9/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LYCEE BEAUMONT DE LOMAGNE&adressechantier=AVENUE DE GASCOGNE&codepostalcommercial=82500&villecommercial=BEAUMONT DE LOMAGNE&telephonecommercial=&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LYCEE BOURDELLE&adressechantier=110 BOULEVARD VINCENT AURIOL&codepostalcommercial=82000&villecommercial=MONTAUBAN&telephonecommercial=&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LYCEE CAPOU&adressechantier=1993 ROUTE DE BORDEAUX&codepostalcommercial=82000&villecommercial=MONTAUBAN&telephonecommercial=&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LYCEE CHARLES DE GAULLE&adressechantier=34 BOULEVARD DE VERDUN&codepostalcommercial=34200&villecommercial=SETE&telephonecommercial=06 47 54 38 91&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=LYCEE JEAN DE PRADES&adressechantier=37 ROUTE DE TOULOUSE&codepostalcommercial=82100&villecommercial=CASTELSARRAZIN&telephonecommercial=05 63 32 84 84&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=14/9/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MAIRIE CLAIRAC REFECTOIRE&adressechantier=LE BOURG RUE DES REBARATS&codepostalcommercial=47230&villecommercial=CLAIRAC&telephonecommercial=06 80 63 39 48&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MAIRIE DE RIA&adressechantier=LIEU DIT L\'USINE&codepostalcommercial=66500&villecommercial=RIA SIRACH&telephonecommercial=06 23 56 52 28&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MAISON BRIAU&adressechantier=AGROPOLE&codepostalcommercial=47310&villecommercial=ESTILLAC&telephonecommercial=05 53 77 02 65&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MANDAVY&adressechantier=LIEU DIT BORDENEUVE&codepostalcommercial=47150&villecommercial=LAUSSOU&telephonecommercial=06 88 56 05 82&surface=726&tarifaumetrecarre=0.75&caht=544.50&datedederniernettoyage=13/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MARAVAL&adressechantier=SALVEPOULE&codepostalcommercial=81440&villecommercial=LAUTREC&telephonecommercial=06 10 19 53 36&surface=594&tarifaumetrecarre=0.75&caht=445.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MARCEL&adressechantier=LIEU DIT BOUDILE&codepostalcommercial=47360&villecommercial=LACEPEDE&telephonecommercial=06 37 92 82 75&surface=726&tarifaumetrecarre=0.75&caht=544.50&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MARRAULD&adressechantier=LIEU DIT POUSTAN&codepostalcommercial=47380&villecommercial=MONCLAR&telephonecommercial=06 87 41 56 28&surface=873&tarifaumetrecarre=0.75&caht=654.75&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MATISOL&adressechantier=RUE NICOLAS APPERT&codepostalcommercial=12000&villecommercial=RODEZ&telephonecommercial=&surface=871&tarifaumetrecarre=0.75&caht=653.25&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=M+ CASTANET&adressechantier=RUE DU DEVELOPPEMENT&codepostalcommercial=31320&villecommercial=CASTANET TOLOSAN&telephonecommercial=&surface=1375&tarifaumetrecarre=0.75&caht=1031.25&datedederniernettoyage=12/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=M+ CORNEBARRIEU&adressechantier=ROUTE DE SEILH&codepostalcommercial=31700&villecommercial=CORNEBARRIEU&telephonecommercial=&surface=860&tarifaumetrecarre=0.75&caht=645&datedederniernettoyage=11/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=M+ FRONTIGNAN&adressechantier=34 AVENUE DE LA MEDIRERRANEE&codepostalcommercial=34110&villecommercial=FRONTIGNAN&telephonecommercial=04 67 80 77 60&surface=432&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=edonada@mplus-materiaux.com',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MIDI TIELLES&adressechantier=ZA LACLAU&codepostalcommercial=34770&villecommercial=GIGEAN&telephonecommercial=04 67 78 69 03&surface=658&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MIN D\'AGEN&adressechantier=MARCHE GARE&codepostalcommercial=47550&villecommercial=BOE&telephonecommercial=&surface=10016&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=20/6/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MINJAT&adressechantier=426 ROUTE DU TEMPLE&codepostalcommercial=33138&villecommercial=LANTON&telephonecommercial=05 56 82 35 69&surface=657&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MONDIN&adressechantier=GRAND BOURDIEU&codepostalcommercial=47600&villecommercial=ESPIENS&telephonecommercial=06 82 02 84 85&surface=714&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MORIN&adressechantier=LES BRUYERES&codepostalcommercial=71130&villecommercial=NEUVY GRANDCHAMP&telephonecommercial=06 26 6 320 19&surface=1303&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=22/4/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=M+ PORTET SUR GARONNE&adressechantier=75 AVENUE D\'Espagne&codepostalcommercial=31120&villecommercial=PORTET SUR GARONNE&telephonecommercial=&surface=820&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=11/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=M+ ROQUES&adressechantier=1004 ROUTE NATIONALE 117&codepostalcommercial=31120&villecommercial=ROQUES&telephonecommercial=&surface=531&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=11/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=MTRE PRUNILLE ST-QUENTIN&adressechantier=LES GROUSSAGNES&codepostalcommercial=47330&villecommercial=ST QUENTIN DU DROPT&telephonecommercial=06 82 82 91 48&surface=9727&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=PERGAS&adressechantier=PARGAS&codepostalcommercial=32480&villecommercial=LA ROMIEU&telephonecommercial=05 62 28 81 92&surface=1550&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=5/9/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=POSSAMAI&adressechantier=LIEU DIT CASTELANDE&codepostalcommercial=33540&villecommercial=GORNAC&telephonecommercial=06 86 96 20 68&surface=1750&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=PROVENCE TOMATES&adressechantier=LE GRAND ROUBIAN&codepostalcommercial=13150&villecommercial=TARASCON&telephonecommercial=04 90 97 26 15&surface=10354&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=21/3/2022&emailcommercial=philippe.cordonnier@provence-tomates.com',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=REDEN SOLAR&adressechantier=ZAC DES CHAMPS DE LESCAZE&codepostalcommercial=47310&villecommercial=ROQUEFORT&telephonecommercial=&surface=14988&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=7/6/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=REVAULT METAIRIE&adressechantier=METAIRIE DE BORDENEUVE&codepostalcommercial=47450&villecommercial=BOE&telephonecommercial=&surface=693&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=REVERDY&adressechantier=LIEU DIT ROUSSANE&codepostalcommercial=47290&villecommercial=BEAUGAS&telephonecommercial=06 87 81 71 23&surface=724&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=13/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ROBERT LITT&adressechantier=375 AVENUE DE L\'HIPPODROME&codepostalcommercial=40000&villecommercial=MONT DE MARSAN&telephonecommercial=06 14 06 57 76&surface=1374&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=17/3/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=ROGER&adressechantier=CONDARIE&codepostalcommercial=81440&villecommercial=LAURTREC&telephonecommercial=06 18 90 27 43&surface=594&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=RPA SANGUINET&adressechantier=CHEMIN DE LILLOT&codepostalcommercial=40460&villecommercial=SANGUINET&telephonecommercial=&surface=968&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=servicestechniques@sanguinet.fr',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=SANS&adressechantier=LACHET&codepostalcommercial=09210&villecommercial=LEZAT SUR LEZE&telephonecommercial=06 30 36 01 70&surface=&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=SCI DU PREGAY&adressechantier=LIEU DIT PREGAY&codepostalcommercial=47800&villecommercial=ALLEMANS DU DROPT&telephonecommercial=06 10 73 79 98&surface=2064&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=SIDV VILLEFRANCHE&adressechantier=RUE DE MONTAUBAN&codepostalcommercial=12200&villecommercial=VILLEFRANCHE DE ROUERGUE&telephonecommercial=05 65 81 13 71&surface=741&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=SOMAG&adressechantier=ZI LAVILLE RUE CLEMENCEAU&codepostalcommercial=47420&villecommercial=BON ENCONTRE&telephonecommercial=&surface=872&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=THERMISOL&adressechantier=ZA DE BEL AIR RUE DES ROUTIERS&codepostalcommercial=12000&villecommercial=RODEZ&telephonecommercial=&surface=584&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=TOUMEYRAGUES FRUIT GOURMET&adressechantier=LIEU DIT PREGAY&codepostalcommercial=47800&villecommercial=ALLEMANS DU DROPT&telephonecommercial=06 10 73 79 98&surface=2064&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=UNICOQUE LOUBERIE 4&adressechantier=LIEU DIT LOUBERIE BATIMENT 4&codepostalcommercial=47290&villecommercial=CANCON&telephonecommercial=0676169174&surface=1848&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=6/1/2022&emailcommercial=jlreigne@unicoque.com',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=UNICOQUE MOULINIE&adressechantier=LIEU DIT LOUBERIE&codepostalcommercial=47290&villecommercial=CANCON&telephonecommercial=&surface=1114&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=6/1/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=VERGE&adressechantier=BARTHAZAC&codepostalcommercial=47700&villecommercial=POUSSIGNAC&telephonecommercial=05 53 83 69 74&surface=724&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=VIARD&adressechantier=RUE DE L\'ARROUX&codepostalcommercial=71160&villecommercial=DIGOIN&telephonecommercial=03 85 88 95 98&surface=7828&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=19/4/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=VIGNERONS DE BUZET&adressechantier=AVENUE DES COTES DE BUZET&codepostalcommercial=47160&villecommercial=BUZET SUR BAISE&telephonecommercial=&surface=7745&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=11/4/2022&emailcommercial=',
  'https://espacepro.jimmys-box.com/wp-json/capvert/solaire-chantier/ajouter?idclient=6589&identitecommercial=VIVIERS DE FRANCE&adressechantier=1031 ROUTE DU BAYLE LIEU DIT SARDINE&codepostalcommercial=40170&villecommercial=SAINT JULIEN EN BORN&telephonecommercial=06 88 08 80 54&surface=12012&tarifaumetrecarre=0.75&caht=&datedederniernettoyage=17/1/2022&emailcommercial='

];

// Use `for...of` loop to iterate through each URL
for (const url of urls) {
  // Send GET request to URL using `fetch()`
  fetch(url)
    .then(response => {
      if (response.ok) {
        // Log the json data of the response to the console
        return response.json().then(data => {
          console.log(data)
        })
      }
    })
    .catch(error => {
      // Log any errors to the console
      console.error(error);
    });
}